#!/usr/bin/python
# TextSecure using SSH Gateway
# Notification via TextSecure using SSH Gateway

import os, sys

def which(program):
    def is_exe(fpath):
        return os.path.isfile(fpath) and os.access(fpath, os.X_OK)

    fpath, fname = os.path.split(program)
    if fpath:
        if is_exe(program):
            return program
    else:
        for path in os.environ["PATH"].split(os.pathsep):
            path = path.strip('"')
            exe_file = os.path.join(path, program)
            if is_exe(exe_file):
                return exe_file

    return None

binary = which('ssh')
textsecure_user = "textsecure"
textsecure_gateway = "textsecure"
textsecure_wrapper = "/var/www/textsecure-gateway/bin/textsecure-wrapper"

if not binary:
    sys.stderr.write('Error: ssh not found\n')
    sys.exit(1)

message = os.environ['NOTIFY_HOSTNAME'] + " "

if os.environ['NOTIFY_WHAT'] == 'SERVICE':
    message += os.environ['NOTIFY_SERVICESTATE'] + " "
    message += os.environ['NOTIFY_SERVICEDESC'] + " "
    message += re.escape(os.environ['NOTIFY_SERVICEOUTPUT'])

else:
    message += "is " + os.environ['NOTIFY_HOSTSTATE']

recipient = os.environ['NOTIFY_CONTACTPAGER']

if not recipient:
    sys.stderr.write('Error: No contact pager set for %s\n' % os.environ['NOTIFY_CONTACTNAME'])
    sys.exit(1)

os.system('%s %s@%s %s --to %s --message \\"%s\\"' % (binary, textsecure_user, textsecure_gateway, textsecure_wrapper, recipient, message))
