#!/usr/bin/python
# TextSecure using HTTP Gateway
# Notification via TextSecure using HTTP Gateway

import os, sys, requests

message = os.environ['NOTIFY_HOSTNAME'] + " "

if os.environ['NOTIFY_WHAT'] == 'SERVICE':
    message += os.environ['NOTIFY_SERVICESTATE'] + " "
    message += os.environ['NOTIFY_SERVICEDESC'] + " "
    message += os.environ['NOTIFY_SERVICEOUTPUT']
else:
    message += "is " + os.environ['NOTIFY_HOSTSTATE']

recipient = os.environ['NOTIFY_CONTACTPAGER']

if not recipient:
    sys.stderr.write('Error: No contact pager set for %s\n' % os.environ['NOTIFY_CONTACTNAME'])
    sys.exit(1)

requests.post(os.environ['NOTIFY_PARAMETER_1'], data={'message': message, 'to': recipient})
