#!/usr/bin/python
# TextSecure (using janimo library)
# Notification via TextSecure using janimo's library (https://github.com/janimo/textsecure/)

import os, sys, re

def which(program):
    def is_exe(fpath):
        return os.path.isfile(fpath) and os.access(fpath, os.X_OK)

    fpath, fname = os.path.split(program)
    if fpath:
        if is_exe(program):
            return program
    else:
        for path in os.environ["PATH"].split(os.pathsep):
            path = path.strip('"')
            exe_file = os.path.join(path, program)
            if is_exe(exe_file):
                return exe_file

    return None

binary = which('textsecure')

if not binary:
    sys.stderr.write('Error: TextSecure binary not found\n')
    sys.exit(1)

# atm, textsecure by janimo can't get location of .config and .storage folders via cmdline
# so we need to change the workdir
binary_path = os.path.split(binary)[0]
os.chdir(binary_path)

message = os.environ['NOTIFY_HOSTNAME'] + " "

if os.environ['NOTIFY_WHAT'] == 'SERVICE':
    message += os.environ['NOTIFY_SERVICESTATE'] + " "
    message += os.environ['NOTIFY_SERVICEDESC'] + " "
    message += re.escape(os.environ['NOTIFY_SERVICEOUTPUT'])

else:
    message += "is " + os.environ['NOTIFY_HOSTSTATE']

recipient = os.environ['NOTIFY_CONTACTPAGER']

if not recipient:
    sys.stderr.write('Error: No contact pager set for %s\n' % os.environ['NOTIFY_CONTACTNAME'])
    sys.exit(1)

os.system('%s -to="%s" -message="%s"' % (binary, recipient, message))
